name: Changelog

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened

jobs:
  changelog:
    if: |
      !contains(github.event.pull_request.head.ref, 'changeset-release') &&
      !contains(github.event.pull_request.labels.*.name, '🤖Skip Changelog')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Setup Node with v16.13.0
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 16.13.0

      - name: Check for Changeset
        run: npx @changesets/cli status --since="origin/main"
